"use client";
import { type NextPage } from "next";
import Head from "next/head";

import React, { useState } from "react";
import { Header } from "y/components/Header";
import { api, RouterOutputs } from "y/utils/api";
import { useSession } from "next-auth/react";
import { NoteEditor } from "y/components/NoteEditor";
import { NoteCard } from "y/components/NoteCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Note Taker Radnou</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

//type of the data we get from the api
type Topic = RouterOutputs["topic"]["getAll"][0];

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);
  //fetch data
  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined, //no input
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectedTopic(selectedTopic ?? data[0] ?? null);
      },
    }
  );
  //create Topic
  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics(); // update the list of topics after creating a new one
    },
  });

  //list of notes
  const { data: notes, refetch: refetchNotes } = api.note.getAll.useQuery(
    {
      topicId: selectedTopic?.id ?? "",
    },
    {
      enabled: sessionData?.user !== undefined && selectedTopic !== null,
    }
  );

  //create note
  const createNote = api.note.create.useMutation({
    onSuccess: () => {
      void refetchNotes(); // update the list of notes after creating a new one
    },
  });
  const deleteNote = api.note.delete.useMutation({
    onSuccess: () => {
      void refetchNotes(); // update the list of notes after creating a new one
    },
  });

  // return <div>{JSON.stringify(topics)}</div>;
  return (
    <div className={"mx-5 mt-5 grid grid-cols-4 gap-2"}>
      <div className={"px-2"}>
        <ul className={"menu rounded-box w-56 bg-base-100 p-2"}>
          {topics?.map((topic) => (
            <li key={topic.id}>
              <a
                href={"#"}
                onClick={(evt) => {
                  evt.preventDefault();
                }}
              >
                {topic.title}
              </a>
            </li>
          ))}
        </ul>
        <div className={"divider"}></div>
        <input
          type={"text"}
          placeholder={"New Topic"}
          className={"input-bordered, input-primary input input-sm   w-full "}
          onKeyDown={(e) => {
            if (e.key == "Enter") {
              createTopic.mutate({
                title: e.currentTarget.value,
              });
              e.currentTarget.value = "";
            }
          }}
        />
      </div>
      <div className={"col-span-3"}>
        <div>
          {notes?.map((note) => (
            <div key={note.id} className={"mt-5"}>
              <NoteCard
                note={note}
                onDelete={() => {
                  void deleteNote.mutate({ id: note.id });
                }}
              />
            </div>
          ))}
        </div>
        <NoteEditor
          // implement the on save function
          onSave={({ title, content }) => {
            void createNote.mutate({
              title,
              content,
              topicId: selectedTopic?.id ?? "",
            });
          }}
        />
      </div>
    </div>
  );
};
