"use client";
import { type NextPage } from "next";
import Head from "next/head";

import React, { useState } from "react";
import { Header } from "y/components/Header";
import { api, RouterOutputs } from "y/utils/api";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Note Taker Radnou</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

//type of the data we get from the api
type Topic = RouterOutputs["topic"]["getAll"][0];

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);
  //fetch data
  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined, //no input
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectedTopic(selectedTopic ?? data[0] ?? null);
      },
    }
  );
  //create Topic
  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics();
    },
  });
  // return <div>{JSON.stringify(topics)}</div>;
  return (
    <div className={"mx-5 mt-5 grid grid-cols-4 gap-2"}>
      <div className={"px-2"}>
        <ul className={"menu rounded-box w-56 bg-base-100 p-2"}>
          {topics?.map((topic) => (
            <li key={topic.id}>
              <a
                href={"#"}
                onClick={(evt) => {
                  evt.preventDefault();
                }}
              >
                {topic.title}
              </a>
            </li>
          ))}
        </ul>
        <div className={"divider"}></div>
        <input
          type={"text"}
          placeholder={"New Topic"}
          className={"input-bordered, input input-sm w-full"}
          onKeyDown={(e) => {
            if (e.key == "Enter") {
              createTopic.mutate({
                title: e.currentTarget.value,
              });
              e.currentTarget.value = "";
            }
          }}
        />
      </div>
      <div className={"col-span-3"}>
        <div>{JSON.stringify(topics)}</div>
      </div>
    </div>
  );
};
